import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/components/Navbar/NavBar";
import "./globals.css";
import { FavoriteProvider } from "@/context/FavoriteContext";
import { ToastProvider } from "@/context/ToastContext";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movieflex",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <FavoriteProvider>
            <NavBar />
            <Suspense>{children}</Suspense>
          </FavoriteProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
